name: lib
version: 0.1.0.0
dependencies:
  - base == 4.*
  - hourglass
  - aeson
  - strict
  - yaml
  - tasty
  - tasty-hunit
  - tasty-hspec
  - tasty-golden
  - temporary
  - directory
  - hspec
  - HUnit
  - bytestring
  - utf8-string
  - megaparsec
  - containers
  - replace-megaparsec
  - parser-combinators
  - text
  - filepath
  - optparse-applicative
  - process
  - process-extras
executables:
  ddgram:
    main: Main.hs
    source-dirs:  app
    dependencies: lib
library:
  source-dirs:   src
tests:
  ddgram-test-suite:
    main: test.hs
    source-dirs: tests
    dependencies: lib
